CREATE TABLE StudentRegister
(DormID VARCHAR(10)  NOT NULL,
	StudentID CHAR(12) NOT NULL,
	StudentName VARCHAR(10) NOT NULL,
	Date DATE,
	Goods VARCHAR(50),
	PRIMARY KEY(DormID,StudentID),
	FOREIGN KEY(DormID) REFERENCES Dorm(DormID)
	ON DELETE CASCADE	
	ON UPDATE CASCADE,
	FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
	ON DELETE CASCADE
	ON UPDATE CASCADE);
