CREATE TABLE DormitoryCheck
(DormID VARCHAR(10) NOT NULL,
	Grade SMALLINT NOT NULL,
	CheckPeople VARCHAR(5),
	CheckDate DATE,
	PRIMARY KEY(DormID,CheckDate),
FOREIGN KEY(DormID) REFERENCES Dorm(DormID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
